### ISSUE TITLE
Benchmark list is failed to be displayed in GUI

### ISSUE THREAD

**Issue by smirnp** [hobbit-project/platform#242]
Hi! 
The online platform have started to fail with loading a list of benchmarks in GUI.

**Comment by earthquakesan** [comment]
Hi @smirnp we had a DNS problem on our side, which is solved now. Thanks for reporting!

**Comment by schadomi7** [comment]
Does not appear to be fully resolved, several benchmarks fail with UnknownHostException:

` "message": "java.net.UnknownHostException: rabbit"`

**Comment by clin99** [comment]
The problem is not solved. The online platform fails to load the list of Benchmarks in GUI now.

**Comment by earthquakesan** [comment]
@clin99 @schadomi7 @smirnp we finally figured out the problem, it should work now.

**Comment by extra3** [comment]
I tried it out a few minutes ago, but it is still not working (at least for me). The Server is not sending an answer for the GET request of the GUI.

**Comment by clin99** [comment]
@earthquakesan  The online platform now fails to load the benchmark list in GUI.

**Comment by MichaelRoeder** [comment]
Yes, we solved one problem but because of #245 the problem got stuck.

Please note that because of server and server room maintenance, we can not solve the problem before Wednesday.
