### ISSUE TITLE
Couldn't pull image

### ISSUE THREAD

**Issue by smirnp** [hobbit-project/platform#379]
Cannot finish any benchmark/system locally and in the online platform. 
Locally get an error, that requested docker images not found (for benchmark and system).

**Comment by smirnp** [comment]
Now it works again for all checked images. Surprisingly

**Comment by vpapako** [comment]
It seems that the same is happening again. None of the benchmark or system images can be pulled from gitlab:

```
2018-12-04 08:32:47,607 ERROR [org.hobbit.controller.docker.ContainerManagerImpl] - <Couldn't pull image git.project-hobbit.eu:4567/papv/versioningevaluationmodule:2.2.1 on node jux2f1eca8gqyfm6a921naza3. No such image: git.project-hobbit.eu:4567/papv/versioningevaluationmodule:2.2.1
...
2018-12-04 08:32:47,049 ERROR [org.hobbit.controller.docker.ContainerManagerImpl] - <Couldn't pull image git.project-hobbit.eu:4567/papv/versioningbenchmarkcontroller:2.2.1 on node q7pyglwpdcw6gslk9vjwdx2i7. No such image: git.project-hobbit.eu:4567/papv/versioningbenchmarkcontroller:2.2.1
...
2018-12-04 08:32:54,626 ERROR [org.hobbit.controller.docker.ContainerManagerImpl] - <Couldn't pull image git.project-hobbit.eu:4567/papv/versioningdatagenerator:2.2.1 on node q7pyglwpdcw6gslk9vjwdx2i7. No such image: git.project-hobbit.eu:4567/papv/versioningdatagenerator:2.2.1>
...
java.lang.Exception: Couldn't pull image on node jqxszqzz5zu90gk2f1jzkvf8a: No such image: git.project-hobbit.eu:4567/gitadmin/basho-riak-kv:1.0.0
...
2018-12-04 08:32:47,832 ERROR [org.hobbit.controller.docker.ContainerManagerImpl] - <Couldn't pull image git.project-hobbit.eu:4567/mspasic/virtuosocomsystem81 on node 3wb9m9nwxpcybj837uzim3w2h. No such image: git.project-hobbit.eu:4567/mspasic/virtuosocomsystem81:latest>
...
2018-12-04 08:32:58,047 ERROR [org.hobbit.controller.docker.ContainerManagerImpl] - <Couldn't pull image git.project-hobbit.eu:4567/papv/versioningtaskgenerator:2.2.1 on node v8se0sug5c3wdw0793xhxuz51. No such image: git.project-hobbit.eu:4567/papv/versioningtaskgenerator:2.2.1>
```

It seems as a gitlab issue, since at the same time I cannot push any image to it:
```
The push refers to repository [git.project-hobbit.eu:4567/papv/versioningevaluationmodule]
Get https://git.project-hobbit.eu:4567/v2/: dial tcp 139.18.121.22:4567: getsockopt: connection refused
```

**Comment by smirnp** [comment]
Cannot push images now (while can run them).
The same error: `Get https://git.project-hobbit.eu:4567/v2/: dial tcp 139.18.121.22:4567: getsockopt: connection refused`

**Comment by smirnp** [comment]
Resolved by @denkv

**Comment by denkv** [comment]
Both `No such image` (when manually running `docker pull` succeeds) and `getsockopt: connection refused` (when Gitlab UI is working fine, but not docker repository it seems) still happen.
